name: Lint and build

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'static/**'
      - 'Dockerfile'
      - 'tsconfig.json'
      - 'yarn.lock'

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo in $GITHUB_WORKSPACE
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache modules
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Build and publish docker image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: flodocks/raincheck-notify
        username: flodocks
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        repository: flodocks/raincheck-notify
        tags: latest
